import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import demo from "@/data/org_demo.json";
import dayjs from "dayjs";

const s = StyleSheet.create({
  page: { padding: 32, fontSize: 11, fontFamily: "Helvetica" },
  h1: { fontSize: 18, marginBottom: 6 },
  h2: { fontSize: 14, marginTop: 18, marginBottom: 6 },
  p: { marginBottom: 4 },
  row: { flexDirection: "row", justifyContent: "space-between" },
  cell: { width: "48%" },
  small: { fontSize: 9, color: "#555" },
  table: { marginTop: 8, borderTop: 1, borderColor: "#ddd" },
  tr: { flexDirection: "row", borderBottom: 1, borderColor: "#eee", paddingVertical: 4 },
  th: { flex: 1, fontSize: 10, fontWeight: 700 },
  td: { flex: 1, fontSize: 10 },
});

export function SecrDoc() {
  const org = (demo as any).org;
  const kpis = (demo as any).kpis;
  const sites = (demo as any).sites || [];
  const now = dayjs().format("YYYY-MM-DD");

  return (
    <Document>
      <Page size="A4" style={s.page}>
        <Text style={s.h1}>Streamlined Energy & Carbon Reporting (SECR)</Text>
        <Text style={s.small}>Generated by ZenVolt • {now}</Text>

        <View style={s.row}>
          <View style={s.cell}>
            <Text style={s.h2}>Company</Text>
            <Text style={s.p}>{org.name}</Text>
            <Text style={s.p}>Sector: {org.sector}</Text>
            <Text style={s.p}>Employees: {org.employees}</Text>
            <Text style={s.p}>Country: {org.country}</Text>
          </View>
          <View style={s.cell}>
            <Text style={s.h2}>Period</Text>
            <Text style={s.p}>Reporting period: {org.reportingPeriod}</Text>
            <Text style={s.p}>Scopes: {org.targets.scopesCovered.join(", ")}</Text>
            <Text style={s.p}>Net zero target year: {org.targets.netZeroYear}</Text>
            <Text style={s.p}>
              Short-term: {org.targets.shortTerm.year} (−{org.targets.shortTerm.reductionVs2020Pct}% vs 2020)
            </Text>
          </View>
        </View>

        <Text style={s.h2}>Energy & Emissions Summary</Text>
        <View style={s.table}>
          <View style={s.tr}>
            <Text style={s.th}>Site</Text>
            <Text style={s.th}>Scope 1 (tCO₂e)</Text>
            <Text style={s.th}>Scope 2 (tCO₂e)</Text>
            <Text style={s.th}>Fleet (tCO₂e)</Text>
            <Text style={s.th}>Energy (kWh)</Text>
            <Text style={s.th}>Renewables %</Text>
          </View>
          {sites.map((site: any) => (
            <View style={s.tr} key={site.siteId}>
              <Text style={s.td}>{site.name}</Text>
              <Text style={s.td}>{site.scope1_tCO2e}</Text>
              <Text style={s.td}>{site.scope2_tCO2e}</Text>
              <Text style={s.td}>{site.fleet_tCO2e}</Text>
              <Text style={s.td}>{site.energy_kwh.toLocaleString()}</Text>
              <Text style={s.td}>{site.renewables_pct}%</Text>
            </View>
          ))}
        </View>

        <Text style={s.h2}>On-chain Evidence (ZenVolt)</Text>
        <Text style={s.p}>Attestations on TRON (PRE): {kpis.onChainAttestations}</Text>
        <Text style={s.p}>Saved emissions recorded: {kpis.onChainSavedKg} kg</Text>
        <Text style={s.p}>
          Estimated credits: {kpis.estCreditsTotal} (Verified {kpis.estCreditsVerified}, Unverified {kpis.estCreditsUnverified})
        </Text>
        <Text style={s.small}>
          Notes: This SECR export includes energy & emissions tables aligned with SECR expectations and optional on-chain evidence pointers (for audit trails).
        </Text>
      </Page>
    </Document>
  );
}
