import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import dayjs from "dayjs";
import type { Decision, Row } from "@/components/council/use-debate";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica" },
  header: { marginBottom: 30 },
  h1: { fontSize: 22, fontWeight: "bold", marginBottom: 4, color: "#059669" },
  h2: { fontSize: 16, fontWeight: "bold", marginTop: 20, marginBottom: 8, color: "#059669" },
  h3: { fontSize: 13, fontWeight: "bold", marginTop: 12, marginBottom: 6 },
  p: { marginBottom: 8, lineHeight: 1.5 },
  small: { fontSize: 9, color: "#666", marginBottom: 2 },
  section: { marginBottom: 16 },
  row: { flexDirection: "row", marginBottom: 4 },
  label: { fontWeight: "bold", width: 80 },
  value: { flex: 1 },
  table: { marginTop: 12, borderTop: 1, borderColor: "#ddd" },
  tableRow: { flexDirection: "row", borderBottom: 1, borderColor: "#eee", paddingVertical: 6 },
  tableHeader: { backgroundColor: "#f3f4f6", fontWeight: "bold" },
  tableCell: { flex: 1, fontSize: 9, paddingHorizontal: 4 },
  tableCellTitle: { flex: 2, fontSize: 9, paddingHorizontal: 4, fontWeight: "bold" },
  bullet: { marginBottom: 6, paddingLeft: 8, lineHeight: 1.4 },
  divider: { borderTop: 1, borderColor: "#ddd", marginVertical: 16 },
  transcriptMessage: { marginBottom: 12, paddingBottom: 8, borderBottom: 1, borderColor: "#eee" },
  transcriptRole: { fontWeight: "bold", fontSize: 10, marginBottom: 4, color: "#059669" },
  transcriptUser: { fontWeight: "bold", fontSize: 10, marginBottom: 4, color: "#dc2626" },
  transcriptContent: { fontSize: 9, lineHeight: 1.4, color: "#333" },
  transcriptTime: { fontSize: 8, color: "#999", marginTop: 2 },
});

type CouncilReportPDFProps = {
  decision: Decision;
  prompt: string;
  messages?: Row[];
  timestamp?: number;
};

export function CouncilReportPDF({ decision, prompt, messages = [], timestamp }: CouncilReportPDFProps) {
  const date = timestamp ? dayjs(timestamp).format("MMMM D, YYYY") : dayjs().format("MMMM D, YYYY");
  const generatedDate = dayjs().format("YYYY-MM-DD");

  // Filter out empty messages and sort by timestamp
  const validMessages = (messages || [])
    .filter((msg) => msg && msg.content && msg.content.trim().length > 0)
    .sort((a, b) => (a.ts || 0) - (b.ts || 0));

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.h1}>AI Council Consensus Report</Text>
          <Text style={styles.small}>Generated by ZenVolt AI Council • {generatedDate}</Text>
        </View>

        {/* Original Question */}
        <View style={styles.section}>
          <Text style={styles.h3}>Original Question</Text>
          <Text style={styles.p}>{prompt}</Text>
          <Text style={styles.small}>Date: {date}</Text>
        </View>

        <View style={styles.divider} />

        {/* Decision Summary */}
        <View style={styles.section}>
          <Text style={styles.h2}>Executive Summary</Text>
          <Text style={styles.h3}>{decision.title || "Council Decision"}</Text>
          <Text style={styles.p}>{decision.rationale || "—"}</Text>
        </View>

        <View style={styles.divider} />

        {/* Discussion Transcript */}
        {validMessages.length > 0 && (
          <>
            <View style={styles.section}>
              <Text style={styles.h2}>Discussion Transcript</Text>
              <Text style={styles.small}>
                Full council discussion leading to this decision ({validMessages.length} messages)
              </Text>
              {validMessages.map((msg, index) => {
                const isUser = msg.agentId === "user";
                const messageTime = msg.ts ? dayjs(msg.ts).format("HH:mm") : "";
                return (
                  <View key={msg.id || index} style={styles.transcriptMessage}>
                    <Text style={isUser ? styles.transcriptUser : styles.transcriptRole}>
                      {msg.role || "Unknown"}
                    </Text>
                    <Text style={styles.transcriptContent}>{msg.content}</Text>
                    {messageTime && <Text style={styles.transcriptTime}>{messageTime}</Text>}
                  </View>
                );
              })}
            </View>
            <View style={styles.divider} />
          </>
        )}

        {/* Action Plan */}
        <View style={styles.section}>
          <Text style={styles.h2}>Action Plan</Text>
          {decision.actions && decision.actions.length > 0 ? (
            <View style={styles.table}>
              {/* Table Header */}
              <View style={[styles.tableRow, styles.tableHeader]}>
                <Text style={[styles.tableCellTitle, { fontSize: 10 }]}>Action</Text>
                <Text style={[styles.tableCell, { fontSize: 10 }]}>Owner</Text>
                <Text style={[styles.tableCell, { fontSize: 10 }]}>Effort</Text>
                <Text style={[styles.tableCell, { fontSize: 10 }]}>Impact</Text>
                <Text style={[styles.tableCell, { fontSize: 10 }]}>Timeline</Text>
              </View>
              {/* Table Rows */}
              {decision.actions.map((action, index) => (
                <View key={index} style={styles.tableRow}>
                  <View style={styles.tableCellTitle}>
                    <Text style={{ fontWeight: "bold", marginBottom: 2 }}>{action.title}</Text>
                    {action.costRange && (
                      <Text style={{ fontSize: 8, color: "#666" }}>Cost: {action.costRange}</Text>
                    )}
                    {action.notes && (
                      <Text style={{ fontSize: 8, color: "#666", marginTop: 2 }}>{action.notes}</Text>
                    )}
                  </View>
                  <Text style={styles.tableCell}>{action.owner}</Text>
                  <Text style={styles.tableCell}>{action.effort}</Text>
                  <Text style={styles.tableCell}>{action.impact}</Text>
                  <Text style={styles.tableCell}>{action.timeline}</Text>
                </View>
              ))}
            </View>
          ) : (
            <Text style={styles.p}>No actions defined.</Text>
          )}
        </View>

        <View style={styles.divider} />

        {/* Risks */}
        <View style={styles.section}>
          <Text style={styles.h2}>Risk Assessment</Text>
          {decision.risks && decision.risks.length > 0 ? (
            decision.risks.map((risk, index) => (
              <Text key={index} style={styles.bullet}>
                • {risk}
              </Text>
            ))
          ) : (
            <Text style={styles.p}>No risks recorded.</Text>
          )}
        </View>

        <View style={styles.divider} />

        {/* Metrics */}
        <View style={styles.section}>
          <Text style={styles.h2}>Success Metrics</Text>
          {decision.metrics && decision.metrics.length > 0 ? (
            decision.metrics.map((metric, index) => (
              <Text key={index} style={styles.bullet}>
                • {metric}
              </Text>
            ))
          ) : (
            <Text style={styles.p}>No metrics defined.</Text>
          )}
        </View>

        {/* Footer */}
        <View style={{ marginTop: 30, paddingTop: 10, borderTop: 1, borderColor: "#ddd" }}>
          <Text style={styles.small}>
            This report was generated by the AI Sustainability Council, a multi-agent system designed to provide
            comprehensive analysis and recommendations for sustainability initiatives.
          </Text>
        </View>
      </Page>
    </Document>
  );
}

